# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: porter.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cporter.proto\x12\x05\x61ries\")\n\tSearchReq\x12\x0f\n\x07Keyword\x18\x01 \x01(\t\x12\x0b\n\x03Top\x18\x02 \x01(\x05\".\n\x0cRecommendReq\x12\x1e\n\x03req\x18\x01 \x01(\x0b\x32\x11.aries.PorterInfo\"\'\n\nPorterInfo\x12\n\n\x02Id\x18\x01 \x01(\t\x12\r\n\x05Title\x18\x02 \x01(\tB\x14\xaa\x02\x11\x61ries.porter.grpcb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'porter_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\021aries.porter.grpc'
  _globals['_SEARCHREQ']._serialized_start=23
  _globals['_SEARCHREQ']._serialized_end=64
  _globals['_RECOMMENDREQ']._serialized_start=66
  _globals['_RECOMMENDREQ']._serialized_end=112
  _globals['_PORTERINFO']._serialized_start=114
  _globals['_PORTERINFO']._serialized_end=153
# @@protoc_insertion_point(module_scope)
